### ISSUE TITLE
I could not make it run on Ubuntu 13.04

### ISSUE THREAD

**Issue by trappedinspacetime** [ofeldt/rubulex#1]
Hi,
First of all thank you for such tool. I tried to install it on my laptop but it won't run. I followed your usage guide. when I run "rubulex" in terminal I get following error :
$ rubulex
fatal: Not a git repository (or any of the parent directories): .git
/var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/resolver.rb:296:in `resolve': Could not find gem 'rspec (~> 2.13.0) ruby' in the gems available on this machine. (Bundler::GemNotFound)
    from /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/resolver.rb:168:in`start'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/resolver.rb:129:in `block in resolve'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/resolver.rb:128:in`catch'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/resolver.rb:128:in `resolve'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/definition.rb:179:in`resolve'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/definition.rb:114:in `specs'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/definition.rb:159:in`specs_for'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:13:in `setup'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler.rb:127:in`setup'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
    from /var/lib/gems/1.9.1/gems/rubulex-0.5.0/bin/rubulex:7:in`<top (required)>'
    from /usr/local/bin/rubulex:23:in `load'
    from /usr/local/bin/rubulex:23:in`<main>'

Would you please help me?

**Comment by ofeldt** [comment]
Hi there,
I'll have a look, later that day and may bounce the version
