### ISSUE TITLE
Positive look ahead regexes doesn't work.

### ISSUE THREAD

**Issue by KevinColemanInc** [ofeldt/rubulex#3]
If your regex has a look ahead matcher, then you can't run the regex again on the match_text and expect the match_text match again. Since sub_match is nil, you can't call `#length` on nil.

The problem line is at https://github.com/ofeldt/rubulex/blob/master/lib/rubulex/regexp_parser.rb#L61

to re-produce:
```ruby
data = "hello, world"
@regex = /hel(?=lo)/
data.gsub(@regex) do |match_text|
  # match_text = 'hel'
  sub_match = match_text.match(@regex)
  puts "ERROR! Sub_match is nil." if sub_match.nil?
end
```

**Comment by ofeldt** [comment]
Hi there!

Thanks for contributing. I merged your changes and bumped a lot of dependencies.

Please check if your changes work correctly.
